name: ci

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Login zu GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3️⃣ QEMU Setup für Multi-Arch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 4️⃣ Docker Buildx Setup
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5️⃣ Build & Push Docker-Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/herzogelias/conduit-backend:latest